const config = {
    API_URL: process.env.NEXT_PUBLIC_POLYSYNERGY_API_URL,
    LOCAL_API_URL: process.env.NEXT_PUBLIC_POLYSYNERGY_LOCAL_API_URL,
    WEBSOCKET_URL: process.env.NEXT_PUBLIC_POLYSYNERGY_WEBSOCKET_URL,
};

export default config;